config/routes.rb
Rails.application.routes.draw do
  resources :bookings, except: [:new, :create]
  resources :voitures do
    resources :bookings, only: :create
  end
  devise_for :users
  root to: "voitures#index"
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'

  end
  get 'current_user_car', to: 'voitures#current_user_car'
  get 'current_user_booking', to: 'bookings#current_user_booking'
  # get 'voitures/:id/edit', to: 'voitures#edit', as: 'edit_voiture'
  delete 'voitures/:id', to: 'voitures#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :voitures do
    post 'reserver', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :voiture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_many :bookings, :voitures
  has_many :bookings, dependent: :destroy
  has_many :voitures, through: :bookings
end

app/models/voiture.rb
class Voiture < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :image, presence: true
  # has_many :bookings, dependant: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nom, :prenom, :adresse, :ville, :code_postal, :photo_de_profil])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:nom, :prenom, :adresse, :ville, :code_postal, :photo_de_profil])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new


  # GET /bookings/1/edit
  def edit
  end



  def create
    @voiture = Voiture.find(params[:voiture_id])
    # @booking = @voiture.bookings.build(booking_params)
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.voiture = @voiture

    @booking.save
    redirect_to current_user_booking_path
    # respond_to do |format|
    #   if @booking.save
    #     format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
    #     format.json { render :show, status: :created, location: @booking }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @booking.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to current_user_booking_path, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def current_user_booking
    @bookings = Booking.where(user_id: current_user.id)
    @bookings = @bookings.reverse
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:date_debut, :date_fin, :valide)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/voitures_controller.rb
class VoituresController < ApplicationController
  before_action :set_voiture, only: %i[ show edit update destroy ]

  # GET /voitures or /voitures.json
  def index
    @voitures = Voiture.all
  end

  # GET /voitures/1 or /voitures/1.json
  def show

    # @booking = Booking.new(voiture: @voiture, user: current_user)
    @booking = Booking.new
  end

  # GET /voitures/new
  def new
    @voiture = Voiture.new
  end

  # GET /voitures/1/edit
  def edit
  end

  # POST /voitures or /voitures.json
  def create
    @voiture = Voiture.new(voiture_params)

    respond_to do |format|
      if @voiture.save
        format.html { redirect_to voiture_url(@voiture), notice: "Voiture was successfully created." }
        format.json { render :show, status: :created, location: @voiture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @voiture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voitures/1 or /voitures/1.json
  def update
    respond_to do |format|
      if @voiture.update(voiture_params)
        format.html { redirect_to voiture_url(@voiture), notice: "Voiture was successfully updated." }
        format.json { render :show, status: :ok, location: @voiture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @voiture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voitures/1 or /voitures/1.json
  def destroy
    @voiture.destroy

    respond_to do |format|
      format.html { redirect_to voiture_path, notice: "Voiture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def current_user_car
    @voitures = Voiture.where(user_id: current_user.id)
  end

  def reserver
    @voiture = Voiture.find(params[:id])
    @booking = Booking.new(voiture: @voiture, user: current_user)

    if @booking.save
      redirect_to @voiture, notice: "La voiture a été réservée avec succès."
    else
      redirect_to @voiture, alert: "La réservation de la voiture a échoué."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voiture
      @voiture = Voiture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def voiture_params
      params.require(:voiture).permit(:marque, :modele, :annee, :description, :annee, :prix, :user_id, :photo, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Date debut:</strong>
    <%= booking.date_debut %>
  </p>

  <p>
    <strong>Date fin:</strong>
    <%= booking.date_fin %>
  </p>

  <p>
    <strong>User:</strong>
    <%= booking.user_id %>
  </p>

  <p>
    <strong>Voiture:</strong>
    <%= booking.voiture_id %>
  </p>

  <p>
    <strong>Valide:</strong>
    <%= booking.valide %>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date_debut %>
    <%= f.input :date_fin %>
    <%# <%= f.association :user %>
    <%# <%= f.association :voiture %>
    <%= f.input :valide %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/current_user_booking.html.erb
<main class="py-24">
  <div class="mx-auto max-w-7xl sm:px-2 lg:px-8">
    <div class="mx-auto max-w-2xl px-4 lg:max-w-4xl lg:px-0">
      <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">Toutes mes réservations</h1>
      <p class="mt-2 text-sm text-gray-500">Retrouvez ici toutes vos réservations de voitures</p>
    </div>
  </div>

  <% @bookings.each do |booking| %>
    <section aria-labelledby="recent-heading" class="mt-16">
      <h2 id="recent-heading" class="sr-only">Dernières réservations</h2>
      <div class="mx-auto max-w-7xl sm:px-2 lg:px-8">
        <div class="mx-auto max-w-2xl space-y-8 sm:px-4 lg:max-w-4xl lg:px-0">
          <div class="border-b border-t border-gray-200 bg-white shadow-sm sm:rounded-lg sm:border">
            <h3 class="sr-only"><time datetime="<%= booking.date_debut %>"><%= booking.date_debut %></time></h3>

            <div class="flex items-center border-b border-gray-200 p-4 sm:grid sm:grid-cols-4 sm:gap-x-6 sm:p-6">
              <dl class="grid flex-1 grid-cols-2 gap-x-6 text-sm sm:col-span-3 sm:grid-cols-3 lg:col-span-2">
                <div>
                  <dt class="font-medium text-gray-900">Date de début</dt>
                  <dd class="mt-1 text-gray-500"><%= booking.date_debut %></dd>
                </div>
                <div class="hidden sm:block">
                  <dt class="font-medium text-gray-900">Date de fin</dt>
                  <dd class="mt-1 text-gray-500">
                    <time datetime="<%= booking.date_fin %>"><%= booking.date_fin %></time>
                  </dd>
                </div>
                <div>
                  <dt class="font-medium text-gray-900">Prix total</dt>
                  <dd class="mt-1 font-medium text-gray-900"><%= booking.voiture.prix %> €</dd>
                </div>
              </dl>

              <div class="relative flex justify-end lg:hidden">
                <div class="flex items-center">
                  <button type="button" class="-m-2 flex items-center p-2 text-gray-400 hover:text-gray-500" id="menu-0-button" aria-expanded="false" aria-haspopup="true">
                    <span class="sr-only">Options for order WU88191111</span>
                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z" />
                    </svg>
                  </button>
                </div>

                <%# <div class="absolute right-0 z-10 mt-2 w-40 origin-bottom-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-0-button" tabindex="-1">
                  <div class="py-1" role="none">
                    <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-0-item-0">View</a>
                    <%# <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-0-item-1">Invoice</a> %>
                  <%# </div>
                </div> %>
              </div>

              <div class="hidden lg:col-span-2 lg:flex lg:items-center lg:justify-end lg:space-x-4">
                <%# <a href="#" class="flex items-center justify-center rounded-md border border-gray-300 bg-white px-2.5 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
                  <span>View Order</span> %>
                  <%= button_to "Annuler cette reservation", booking, class:"rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", method: :delete %>
                  <%# <span class="sr-only">WU88191111</span> %>
                <%# </a> %>
                <%# <a href="#" class="flex items-center justify-center rounded-md border border-gray-300 bg-white px-2.5 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
                  <span>View Invoice</span>
                  <span class="sr-only">for order WU88191111</span>
                </a> %>
              </div>
            </div>

            <h4 class="sr-only">Items</h4>
            <ul role="list" class="divide-y divide-gray-200">
              <li class="p-4 sm:p-6">
                <div class="flex items-center sm:items-start">
                  <div class="h-20 w-20 flex-shrink-0 overflow-hidden rounded-lg bg-gray-200 sm:h-40 sm:w-40">
                    <%= image_tag booking.voiture.image, class: "h-full w-full object-cover object-center" %>
                  </div>
                  <div class="ml-6 flex-1 text-sm">
                    <div class="font-medium text-gray-900 sm:flex sm:justify-between">
                      <h5><%= booking.voiture.marque %> <%= booking.voiture.modele %></h5>
                    </div>
                    <p class="hidden text-gray-500 sm:mt-2 sm:block"><%= booking.voiture.description %></p>
                  </div>
                </div>

                <div class="mt-6 sm:flex sm:justify-between">
                  <div class="flex items-center">
                    <svg class="h-5 w-5 text-green-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
                    </svg>
                    <p class="ml-2 text-sm font-medium text-gray-500">Date de réservation <time datetime="<%= booking.created_at %>"><%= booking.created_at %></time></p>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  <% end %>
</main>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= link_to "Back to bookings", bookings_path %>

  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<div class="bg-gray-900 py-24 sm:py-32">
  <div class="mx-auto max-w-7xl px-6 lg:px-8">
    <div class="mx-auto max-w-2xl lg:max-w-none">
      <div class="text-center">
        <h2 class="text-3xl font-bold tracking-tight text-white sm:text-4xl">Le meilleur site au monde</h2>
        <p class="mt-4 text-lg leading-8 text-gray-300">Le plus grand choix de véhicules.</p>
      </div>
      <dl class="mt-16 grid grid-cols-1 gap-0.5 overflow-hidden rounded-2xl text-center sm:grid-cols-2 lg:grid-cols-4">
        <div class="flex flex-col bg-white/5 p-8">
          <dt class="text-sm font-semibold leading-6 text-gray-300">Voitures disponibles</dt>
          <dd class="order-first text-3xl font-semibold tracking-tight text-white">8,000+</dd>
        </div>
        <div class="flex flex-col bg-white/5 p-8">
          <dt class="text-sm font-semibold leading-6 text-gray-300">Des frais minimes</dt>
          <dd class="order-first text-3xl font-semibold tracking-tight text-white">3%</dd>
        </div>
        <div class="flex flex-col bg-white/5 p-8">
          <dt class="text-sm font-semibold leading-6 text-gray-300">Satisfaction client</dt>
          <dd class="order-first text-3xl font-semibold tracking-tight text-white">99.9%</dd>
        </div>
        <div class="flex flex-col bg-white/5 p-8">
          <dt class="text-sm font-semibold leading-6 text-gray-300">Revenu moyen </dt>
          <dd class="order-first text-3xl font-semibold tracking-tight text-white">$1M</dd>
        </div>
      </dl>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button -->
        <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!-- Icon when menu is closed -->
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!-- Icon when menu is open -->
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
        <%= link_to root_path do %>
          <img class="block h-8 w-auto lg:hidden" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
          <img class="hidden h-8 w-auto lg:block" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company"> <% end %>
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <%= link_to "Accueil", root_path, class: "bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium" %>
            <%= link_to "New voiture", new_voiture_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
            <%= link_to "Mes voitures", current_user_car_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>

            <%= link_to "Mes réservations", current_user_booking_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>

            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button type="button" class="rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
          <span class="sr-only">View notifications</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
          </svg>
        </button>

        <!-- Profile dropdown -->
        <div class="relative ml-3" data-controller="dropdown">
          <div >
            <button type="button" class="flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="sr-only">Open user menu</span>
              <img class="h-8 w-8 rounded-full"  data-action="click->dropdown#hide"  data-dropdown-target="avatar" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
            </button>
          </div>

          <div class="d-none absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"   data-dropdown-target="michel" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
            <%# <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a> %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "block px-4 py-2 text-sm text-gray-700", role: "menuitem", tabindex: "-1", id: "user-menu-item-2" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pb-3 pt-2">
      <%= link_to "New voiture", new_voiture_path, class:"bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium" %>
      <%= link_to "Mes voitures", current_user_car_path, class:"bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium" %>
      <%= link_to "mes reservations", root_path, class:"bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium" %>
      <%= link_to "Sign out",destroy_user_session_path, class:"bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium" %>
    </div>
  </div>
</nav>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<h1>TEST 2506 </H1>
<h1 class="text-3xl font-bold underline">
    Hello world!
</h1>
<% @voitures.each do |voiture|%>
<%= voiture.marque %>
<%= voiture.modele %>
<%= voiture.prix %>
<%= voiture.photo %>
<%= end %>

app/views/voitures/_form_booking.html.erb
<%= simple_form_for([@voiture, @booking], url: voiture_bookings_path(@voiture), method: :post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date_debut %>
    <%= f.input :date_fin %>
    <%# <%= f.input :valide %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/voitures/current_user_car.html.erb
<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <h2 class="text-xl font-bold text-gray-900">Mes voitures</h2>

    <div class="mt-8 grid grid-cols-1 gap-y-12 sm:grid-cols-2 sm:gap-x-6 lg:grid-cols-4 xl:gap-x-8">
      <% @voitures.each do |voiture| %>
        <div>
          <div class="relative">
            <div class="relative h-72 w-full overflow-hidden rounded-lg">
              <%= image_tag voiture.image, class: "h-full w-full object-cover object-center" %>
            </div>
            <div class="relative mt-4">
              <h3 class="text-sm font-medium text-gray-900"><%= voiture.marque %></h3>
              <p class="mt-1 text-sm text-gray-500"><%= voiture.modele %></p>
            </div>
            <%= link_to voiture_path(voiture),class:"absolute inset-x-0 top-0 flex h-72 items-end justify-end overflow-hidden rounded-lg p-4" do %>
            <div >
              <div aria-hidden="true" class="absolute inset-x-0 bottom-0 h-36 bg-gradient-to-t from-black opacity-50"></div>
              <p class="relative text-lg font-semibold text-white"><%= voiture.prix %> € / jour</p>
            </div> <% end %>
          </div>

<%# <button type="button" class="inline-flex items-center gap-x-2 rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">

  <svg class="-mr-0.5 h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">

    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
  </svg>
</button> %>
<%= link_to "Modifier", edit_voiture_path(voiture), class:"rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>


 <%= button_to "Destroy this voiture", voiture, class:"rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cette voiture ?" } %>

          <%# <div class="mt-6">
            <a href="#" class="relative flex items-center justify-center rounded-md border border-transparent bg-gray-100 px-8 py-2 text-sm font-medium text-gray-900 hover:bg-gray-200">Booking<span class="sr-only">, Zip Tote Basket</span></a>
          </div> %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/voitures/edit.html.erb
<h1>Editing voiture</h1>

<%= render "form"%>

<br>

<div>
  <%= link_to "Show this voiture", @voiture %> |
  <%= link_to "Back to voitures", voitures_path %>
</div>

app/views/voitures/new.html.erb
<h1>New voiture</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to "Back to voitures", voitures_path %>
</div>